# Generated by Django 6.0.6 on 2026-06-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilaluno',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=14, unique=True),
        ),
    ]
