# Generated by Django 6.0.6 on 2026-06-20 21:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_perfilaluno_cpf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilaluno',
            name='tipo_usuario',
            field=models.CharField(choices=[('aluno', 'Aluno'), ('instrutor', 'Instrutor'), ('admin', 'Admin')], default='aluno', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfilaluno',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
        migrations.AddConstraint(
            model_name='perfilaluno',
            constraint=models.UniqueConstraint(condition=models.Q(('cpf', ''), _negated=True), fields=('cpf',), name='unique_non_empty_cpf'),
        ),
    ]
