# Generated by Django 6.0.6 on 2026-06-20 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('teorica', 'Teorica'), ('pratica', 'Pratica'), ('exame', 'Exame')], max_length=20)),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('concluido', 'Concluido'), ('cancelado', 'Cancelado')], default='agendado', max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('categoria', models.CharField(default='B', max_length=20)),
                ('instrutor', models.CharField(blank=True, max_length=120)),
                ('local', models.CharField(blank=True, max_length=160)),
                ('avaliado', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'agendamento',
                'verbose_name_plural': 'agendamentos',
                'ordering': ['data', 'horario'],
            },
        ),
    ]
