# Generated by Django 6.0.6 on 2026-06-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('agendado', 'Agendado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='agendado', max_length=20),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='tipo',
            field=models.CharField(choices=[('teorica', 'Teórica'), ('pratica', 'Prática'), ('exame', 'Exame')], max_length=20),
        ),
    ]
