# Generated by Django 6.0.6 on 2026-06-20 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='certificados/')),
                ('emitido_em', models.DateTimeField(auto_now_add=True)),
                ('previsao', models.CharField(blank=True, max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'certificado',
                'verbose_name_plural': 'certificados',
                'ordering': ['-emitido_em'],
            },
        ),
        migrations.CreateModel(
            name='ProgressoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aulas_teoricas_total', models.IntegerField(default=45)),
                ('aulas_teoricas_concluidas', models.IntegerField(default=0)),
                ('aulas_praticas_total', models.IntegerField(default=20)),
                ('aulas_praticas_concluidas', models.IntegerField(default=0)),
                ('exame_status', models.CharField(default='aguardando', max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progresso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'progresso de aluno',
                'verbose_name_plural': 'progressos de alunos',
            },
        ),
    ]
