# Generated by Django 6.0.6 on 2026-06-20 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ['titulo'], 'verbose_name': 'avaliação', 'verbose_name_plural': 'avaliações'},
        ),
        migrations.AlterModelOptions(
            name='resultadoavaliacao',
            options={'ordering': ['-data_realizacao'], 'verbose_name': 'resultado de avaliação', 'verbose_name_plural': 'resultados de avaliações'},
        ),
    ]
